### ISSUE TITLE
Saving plot to file

### ISSUE THREAD

**Issue by Spica-Vir** [crystal-code-tools/CRYSTALpytools#103]
Dear @Filo3dg  ,

Just wondering why save fig option is removed?

Thanks

**Comment by Filo3dg** [comment]
Hi @Spica-Vir ,

This is part of a broader refactoring of the code inspired by a couple of users' feedbacks requiring a greater freedom in the plot manipulation. Thus, we decided to return the figure object allowing the users to modify the plot at their liking. In the coming days a series of PR will follow up this one to complete this refactoring operation.

Best

**Comment by Spica-Vir** [comment]
Hi @Filo3dg 

Understood. I'll hold my updates then until you refactor plot functions. Thanks! 

Kind regards
