### ISSUE TITLE
Error when using cry_pmg2gui with dimensionality 2

### ISSUE THREAD

**Issue by bcamino** [crystal-code-tools/CRYSTALpytools#110]
Hi @Spica-Vir ,

I noticed this error in the convert.py module:

    507                 # Then center at z=0.0
    508                 translation = np.array([0.0, 0.0, -0.5])
--> 509                 structure.translate_sites(list(range(structure.num_sites)),
    510                                           translation, to_unit_cell=False)
    511 

NameError: name 'latt_mx' is not defined

When trying to create a GUI object using 

cry_pmg2gui(structure,pbc=[True,True,False],symmetry=True)

I think it's just that latt_mx is not defined within the cry_pmg2gui function. Could you please have a look at it?

Cheers,

bruno

**Comment by Spica-Vir** [comment]
@bcamino Thanks for identifying this issue. Now it should have been fixed
