### ISSUE TITLE
Code suggestion

### ISSUE THREAD

**Issue by lfmvalle** [crystal-code-tools/CRYSTALpytools#114]
Hello there.

I'm onto Materials Sciences (and CRYSTAL itself) very recently. I was diving into some codes of the library, as a way to help me learn Python and to develop some scripts for personal uses, when I've found something strange.

Where?
- **CRYSTALpytools.convert** module
- **cry_gui2pmg** function
- Line 176

What?
A _Pymatgen Structure_ object is returned (as expected from this function), but there are more code implemented after it (an _if_ statement for _dimensionality=3_ cases).

As everything below line 176 never gets executed because the function already hit a return statement, I think this can lead to unexpected behaviors when using dimensionality=3.

That's pretty much about it.

Best regards!
Luiz.

**Comment by crystal-code-tools** [comment]
Dear Luiz, 

Sorry for the late response. You are quite right. Thank you for pointing it out. We can now confirm that code left behind line 176 are redundant and shoud be removed. If you are using 3D periodicity that should be fine but not for lower dimensions. The issue will be left open until it is merged to the new release. Thank you for your contributions!

Kind regards
CPYTools developers

**Comment by crystal-code-tools** [comment]
Dear Luiz,

It should have been fixed by the latest release v2024.11.2. Please refer to the 2D testing cases of [this example](https://crystal-code-tools.github.io/CRYSTALpytools/examples/convert/convert.html#The-'cry_gui2pmg'-function). 

Happy coding!

Best,
CPYTools developers
