### ISSUE TITLE
convert.py : gui2pmg2cif and symmetry

### ISSUE THREAD

**Issue by iclnmh** [crystal-code-tools/CRYSTALpytools#66]
I noticed that in the journey d12/out --> gui then  gui2pmg then pmg2cif that the symmetry information is effectively lost and the cif file adopts P1. This is not ideal. I realise it is a consequence of the gui format not supporting a HM-symbol or space group number. 

Some ideas on how to fix.

For 3D periodic:

1. For bulk structures I have utilities (coded in C++) that perform gui2cif and cif2gui reliably
2. in gui2pmg could pymatgen.SymmetryAnalyser be used to restore the space group information ?
3. We could redefine the gui format as (frustratingly) CRYSTAL often does know the space group
4. I believe that the cif standard does support provision of the symmetry operators only without specifying the space group number or symbol so we could change the behaviour of pmg.CIFwriter to be more flexible (ie: support a .gui like approach)

- any thoughts  ?

Also:
 Aren't the comments in the code wrong. For instance cry_pmg2gui converts a pmg structure to a gui structure but the comments say the opposite ?

And: 
 In pmg2gui it seems you can feed in a 3D structure and by setting dim=2 or 1 it just edits the latvecs ? What is that for, surely we would cut a slab to convert 3D to 2D....

Sorry for the long post.

**Comment by Spica-Vir** [comment]
Hi, yes this is also observed from us. Thanks for pointing this out.  I am testing on my branch and will open a PR when I finish that. Before that I'll leave this issue open. 
Huanyu

**Comment by Spica-Vir** [comment]
P.S. The current solution from me is using pymatgen to get symmetry info.

**Comment by bcamino** [comment]
Hi Nic and Huanyu,

I hope you are well.

CRYSTALpytools goes from the GUI file to a cif by using the cry_gui2pmg function first and then using the CifWriter on the pymatgen Structure object. I see that the "write_file" function in CifWriter has a symprec option set=None by default. This option "If not none, finds the symmetry of the structure and writes the cif with symmetry information. Passes symprec to the SpacegroupAnalyzer.". It also has the "refine_struct " which allows the user to select the primitive or conventional.

@iclnmh, do you think this could be an acceptable fix? @Spica-Vir , this might not work for cases like the paracetamol one where more than one symmetry is possible (although maybe the refine_struct option could help?).

As for the question about pmg2gui, this function is used to transform a Structure object representing a slab in 3D (with vacuum) into a CRYSTAL gui slab file. It sets the c lattice param=500 and removes the symmops that have z components.

Cheers,

Bruno

**Comment by Spica-Vir** [comment]
@bcamino Using refine_structrure seems to work nicely with low-symmetry structures that I have right now. I checked the source code of CifWriter (because strangely SpaceGroupAnalyzer does not give the correct unit cell but CifWriter does). Many thanks for pointing this out. 

@iclnmh I think other questions proposed are addressed. Code and comment on my branch are already updated and will be merged to the main branch soon. Thank you for the discussion and I'll close this issue for now. Please feel free to reopen it if you have any other questions
