### ISSUE TITLE
How this compares to the other Python alternatives

### ISSUE THREAD

**Issue by blokhin** [crystal-code-tools/CRYSTALpytools#74]
Cari Colleghi,

there are also the following similar initiatives known:

- https://github.com/chrisjsewell/ejplugins
- https://github.com/tilde-lab/pycrystal
- https://github.com/nomad-coe/nomad-parser-crystal

Say we, someone wants to select a Python library for the CRYSTAL, could we somehow help them to make an informed decision?

**Comment by blokhin** [comment]
also this [JavaScript project](https://crysplot.crystalsolutions.eu/js/crysplot.js) deserves attention, given its authors are fine with that

**Comment by bcamino** [comment]
Dear @blokhin ,

Thank you for raising this interesting point.

The purpose of the CRYSTALpytools project is to facilitate workflows that involve:
- building structures in python (eg: ASE, pymatgen) then computing and analysing properties using CRYSTAL-23. 
- reading output files from CRYSTAL to extract optimised geometry, final energies, thermodynamic properties, etc.

It is a rapidly growing collection of tools from the developers of CRYSTAL. It does not at this point seek to provide extensive 3D visualisation capabilities which are provided by the javaScript project on the CRYSTAL website and other codes. The other three packages you mentioned seem to be aimed at data analysing and storage, which parses CRYSTAL outputs and store them in a machine-readable format to be integrated into workflow management codes.

Currently, the data in CRYSTALpytools is not printed out in a certain format to keep its interactive and lightweight feature. For example, it represents the backend for the development of Jupyter Notebooks like the ones here (and here in the near future). If this is what you want to do then CRYSTALpytools is a good starting point. 

We will be grateful for any suggestions and feedback you have about the tools.

Kind Regards,

Bruno

**Comment by bcamino** [comment]
Dear @blokhin, I am going to close this issue. Please feel free to reopen it should you have any further questions.

Kind Regard,

Bruno
