### ISSUE TITLE
Dependency of Basis set exchange

### ISSUE THREAD

**Issue by Spica-Vir** [crystal-code-tools/CRYSTALpytools#75]
@bcamino Dear Bruno, I heard feedbacks that the dependency of basis set exchange package is not correctly implemented. Would you mind rechecking that?

**Comment by bcamino** [comment]
Hi @Spica-Vir , I had this issue yesterday and I was going to message you about it. It was solved for me when I installed the basis set exchange package using pip. It's just a matter of adding it to the setup/requirements. You can add it to the PR you have open a dn I will review all together.

Cheers,

Bruno

**Comment by Spica-Vir** [comment]
@bcamino I think the dependency problem has been addressed. It passes the workflow on my branch. I'll close this issue for now. Please let me know if there is any other problem.
