### ISSUE TITLE
ONELOG in optgeom part of input file

### ISSUE THREAD

**Issue by bcamino** [crystal-code-tools/CRYSTALpytools#76]
Hi @Spica-Vir ,

I hope you are well.

Thanks for improving the input part of the CRYSTALtools. It's much better now. I just wasn't able to have the "ONELOG" keyword in the OPTGEOM part of the input. Could you help wth that?

Cheers,

Bruno

**Comment by Spica-Vir** [comment]
Hi Bruno, 

Not all the keywords are implemented. I'll add that keyword and open a new pr

**Comment by bcamino** [comment]
Thank you!
